### ISSUE TITLE
Problemas en la conexion con la bd en consultas largas

### ISSUE THREAD

**Issue by ghost** [rmp1007/GESPRO_GESTIONTAREAS-#12]

**Comment by ghost** [comment]
Se consigue algo de mejor conectividad, pero completa

**Comment by rmp1007** [comment]
Se testea si es culpa de la carga del servidor y no lo es

**Comment by ghost** [comment]
Se consiguen ganar varios segundos

**Comment by rmp1007** [comment]
Se cambia de motor de bd dado que es imposible obtener rendimiento con la anterior
